# Read about `build.yaml` at https://pub.dartlang.org/packages/build_config
targets:
  $default:
    builders:
      exporter|exporterCollector:
        enabled: true
#      exporter|exporterCombiner:
#        enabled: true
builders:
  exporter|exporterCollector:
    import: 'package:exporter/src/builder/builder.dart'
    builder_factories: ['exporterCollector']
    build_extensions: { '.dart': ['.exporter.json'] }
    auto_apply: root_package
    build_to: cache
  exporter|exporterCombiner:
    import: 'package:exporter/src/builder/builder.dart'
    builder_factories: ['exporterCombiner']
    build_extensions: { 'main.dart': ['/generated/exporter.dart'] }
    auto_apply: root_package
    build_to: source
    required_inputs: [".exporter.json"]
