builders:
  exporter|locator:
    import: 'package:generated_locator/src/builder.dart'
    builder_factories: ['extraLocatorBuilder']
    build_extensions: { 'pubspec.yaml': ['exporter.extra_locator'] }
    auto_apply: root_package
    build_to: cache
    defaults:
      generate_for:
        include:
          - pubspec.yaml
        exclude:
          - lib/**
      options:
        extra_locator_name: exporter
  exporter|collector:
    import: 'package:exporter/src/builder/builder.dart'
    builder_factories: ['exporterCollector']
    build_extensions: { '.dart': ['.exporter.json'] }
    auto_apply: root_package
    build_to: cache
  exporter|combiner:
    import: 'package:exporter/src/builder/builder.dart'
    builder_factories: ['exporterCombiner']
    build_extensions: { 'exporter.locator': ['exporter.dart'] }
    auto_apply: root_package
    build_to: source
    required_inputs: [".exporter.json"]
