name: exporter
description: >
  A library generates a single export.
version: 0.1.0
homepage: https://github.com/dart-ecosystem/exporter.dart
author: Copydog <775150@qq.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  build: ^1.2.2
  source_gen: ^0.9.4+6
  glob: ^1.2.0

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.6.0
  build_runner: any
