name: exporter
description: >
  A library generates a single export.
version: 1.0.1
homepage: https://github.com/dart-ecosystem/exporter.dart
author: Copydog <775150@qq.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  build: ^1.2.2
  glob: ^1.2.0
  matchable_builder: ^0.3.1
  generated_locator: ^1.1.0
  path: ^1.6.4

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.6.0
  build_runner: any
